Ouranosinc/pavics-sdi

docs/source/dev/configuration.rst, docs/source/dev/index.rst, docs/source/dev/installation.rst
In the interest of readability, I'm starting a new branch that restructures the major sections, encapsulates old debugging messages, and attempts to unify the tone of the PAVICS documentation throughout. I'll be working on this branch to streamline what we have to better satisfy goals of #15 as well. Please add suggestions, commentary, or direction here.
Immediate questions:
* Which birds are needed for a barebones PAVICS deployment?
* For individual bird *descriptions*, is it good practice to link to existing RtD pages hosted via Birdhouse?
* Who are we directing the documentation towards? (Climate Scientists / Developers / Enthusiasts)?
* Front end and Back end sections: Can this information be adapted from old PAVICS presentations?
* For test developments, are there any low-hanging …
=> Restructuring of Documentation Layout

docs/source/notebooks/climate_indices.ipynb, docs/source/notebooks/opendap.ipynb, docs/source/notebooks/subsetting.ipynb
See build on prod Jenkins http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/feature%252Ftest-more-repos-more-pavics-hosts-and-various-improvements/3/console. Note this build is building this `feature/get_esfg_auth_from_envvar` branch and not `master` so we can now target the branch we want.
It got past the authentication issue but now is failing with `IndexError: too many indices for array`, is that expected?
=> opendap.ipynb: get ESGF auth from environment var to avoid hardcode in notebook

docs/source/notebooks/catalog_search.ipynb, docs/source/notebooks/opendap.ipynb
Fix Jenkins error:
```
'Help on meth...h result.\n\n' == 'Help on meth...h result.\n\n'
Skipping 66 identical leading characters in diff, use -v to show
Skipping 1283 identical trailing characters in diff, use -v to show
- ch(facets=None, shards='*', offset=None, limit=None, fields='*', format='application/solr+json', query='*', distrib=None, type='Dataset', constraints=None, esgf=None, list_t
?                                    ^^^^        ^^^^                                                                 ^^^                                          ^^^
+ ch(facets='None', shards='*', offset=0, limit=0, fields='*', format='application/solr+json', query='*', distrib=False, type='Dataset', constraints='None', esgf=False, list_t
? …
```
=> catalog_search.ipynb: update to match new pavics/pavics-datacatalog:0.6.11

docs/source/notebooks/finch.ipynb
On slow system, intermittently, we see this Jenkins error (note the "32% Done"
line added):
```
_________ pavics-sdi-master/docs/source/notebooks/finch.ipynb::Cell 7 __________
Cell 7: Cell outputs differ
Input:
print(log)
Traceback:
mismatch 'stdout'
'Processing s...cessfully\n\n' == 'Processing s...cessfully\n\n'
Skipping 261 identical leading characters in diff, use -v to show
1.0s
+ [####           ] | 32% Done |100% Done |  1.0s
[###############] | 100% Done |  1.0s|100% Done |  1.0s
Processing finished successfully
```
=> finch.ipynb: ignore output in last print(log) to fix intermittent Jenkins failure

docs/source/notebooks/catalog_search.ipynb
Make the query much more precise by adding "institute:CCCma,model:CanESM2".
Previous query was returning 200+ results after new crawl triggered in https://github.com/bird-house/birdhouse-deploy/pull/4#issuecomment-587163363.
Now we seems to have duplicate result, "cccma" and "CCCMA".  @huard did we rename "CCCMA" to "cccma" on Thredds?
New working Jenkins run: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/480/console
Jenkins error fixed:
```
00:35:48  _____ pavics-sdi-master/docs/source/notebooks/catalog_search.ipynb::Cell 1 _____
00:35:48  Notebook cell execution failed
00:35:48  Cell 1: Cell outputs differ
00:35:48
00:35:48  Input:
00:35:48  resp = wps.pavicsearch(constraints="variable:tasmin,project:CMIP5,experiment:rcp85,frequency:day", limit=10, type="File") …
```
=> catalog_search.ipynb: fix jenkins failure after new crawl

docs/source/arch/jupyter.rst, docs/source/index.rst
Computing resources of the demo account has also been limitted for security reasons.
See PR https://github.com/bird-house/birdhouse-deploy/pull/35 (commit https://github.com/bird-house/birdhouse-deploy/commit/63c8c356f0eadb3b0cf9fb4eea4fff6846bb5d78).
=> Remove hardcode public/public JupyterLab login since it is now configurable for security reasons

docs/source/notebooks/catalog_search.ipynb
Fixes https://github.com/Ouranosinc/pavics-sdi/issues/147
This notebook is a good round trip testing for
* crawler can crawl data on Thredds
* crawler can insert proper data in Solr DB
* catalog search is able to query Solr DB to retrieve the expected data
With the query requiring only the minimum data on Thredds that was already needed by other notebooks, this notebook should pass on all deployments of PAVICS given the minimum test data is available and the crawler has been triggered.
=> catalog_search.ipynb: rewrite query so the data needed on Thredds server is minimum

docs/source/notebooks/jupyter_extensions.ipynb
Documentation for the new jupyterlab extensions we are adding
This notebook will give easily accessable documentation for the user, and will give an overview of what he can do with the extensions.
Matching PR Ouranosinc/PAVICS-e2e-workflow-tests#54 for the new image with 4 new extensions: jupytext, jupyterlab-google-drive, jupyter_conda and jupyterlab-git
Matching PR bird-house/birdhouse-deploy#97 for jupyterlab-google-drive deployment config.
=> Notebook extensions

docs/source/notebooks/catalog_search.ipynb
The change is 'None' to None (without the surrounding quote).
Jenkins error due to upgrade from pavics/workflow-tests:201111 to pavics/workflow-tests:201214 (PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/56)
```
_____ pavics-sdi-master/docs/source/notebooks/catalog_search.ipynb::Cell 0 _____
Cell 0: Cell outputs differ
Input:
import collections
from birdy import WPSClient
url = "https://pavics.ouranos.ca/twitcher/ows/proxy/catalog/wps"
wps = WPSClient(url)
help(wps.pavicsearch)
Traceback:
mismatch 'stdout'
'Help on meth...h result.\n\n' == 'Help on meth...h result.\n\n'
Skipping 66 identical leading characters in diff, use -v to show
- ch(facets=None, shards='*', offset=0, limit=0, fields='*', …
```
=> catalog_search.ipynb: fix help() output change that broke Jenkins

README.rst
Top level link refers to really out of date docs compared to repo content. 
Add it for quick reference.
=> add the readthedocs link to top readme

docs/source/notebooks/pavics_thredds.ipynb
This reverts commit 6ab2ae8e55604caf2bfa776a27eafeffcff40581, reversing changes made to 947ea406881585d475a09e99ae504a0b7d4f9b6d.
Production has not been upgraded to the broken Magpie (PR https://github.com/bird-house/birdhouse-deploy/pull/107) so this revert is so that Jenkins pass again on production.
Jenkins build: https://daccs-jenkins.crim.ca/job/PAVICS-e2e-workflow-tests/job/master/242/console
The `finch-usage.ipynb` failure is due to https://github.com/bird-house/finch/pull/161#discussion_r601975311, a new Finch will be deployed to prod soon (https://github.com/bird-house/birdhouse-deploy/pull/138).  Otherwise, with this revert, production will be green.
The original https://github.com/Ouranosinc/pavics-sdi/pull/209 is back in branch …
=> Revert "Merge pull request #209 from Ouranosinc/magpie-unauthorized-thredds"

docs/source/notebooks/WMS_example.ipynb
For this Jenkins build error (a new `layer.timepositions` is available):
```
______ pavics-sdi-master/docs/source/notebooks/WMS_example.ipynb::Cell 3 _______
Cell 3: Cell outputs differ
Input:
from IPython.core.display import HTML
name = 'MOD_143D_RR'
layer = wms.contents[name]
print("Abstract: ", layer.abstract)
print("BBox: ", layer.boundingBoxWGS84)
print("CRS: ", layer.crsOptions)
print("Styles: ", layer.styles)
print("Timestamps: ", layer.timepositions)
HTML(layer.parent.abstract)
Traceback:
mismatch 'stdout'
"Abstract:  N.../DATE/P1D']\n" == "Abstract:  N...021-04-20']\n"
Skipping 956 identical leading characters in diff, use -v to show
- /DATE/P1D', '2021-04-20']
+ /DATE/P1D']
```
=> WMS_example.ipynb: ignore output to not break Jenkins in the future for similar change

docs/source/notebooks/subset-user-input.ipynb
Any NCML catalogs have to come from the production server since that's too much data to replicate to all the various test servers.
So the catalog string have to hardcode `pavics.ouranos.ca` and use the marker `TEST_USE_PROD_DATA`, all on the same line.
Fix this kind of error:
```
OSError: [Errno -70] NetCDF: DAP server error: b'https://medus.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/datasets/gridded_obs/nrcan_v2.ncml'
```
Also require corresponding PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/86 to work properly.
=> subset-user-input.ipynb: fix for Jenkins to run against test servers

docs/source/notebooks/pavics_thredds.ipynb
Fix the following Jenkins error with new Jupyter env from PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/94:
```
_____ pavics-sdi-master/docs/source/notebooks/pavics_thredds.ipynb::Cell 2 _____
Cell 2: Cell execution caused an exception
Input:
from webob.exc import HTTPError
SECURED_URL = f"{THREDDS_URL}/dodsC/birdhouse/testdata/secure/tasmax_Amon_MPI-ESM-MR_rcp45_r2i1p1_200601-200612.nc"
try:
ds = xr.open_dataset(SECURED_URL, decode_cf=False)
except OSError as exc:  # xarray < 0.17
assert "Authorization failure" in str(exc)
except HTTPError as exc: # xarray >= 0.17
assert "401 Unauthorized" in str(exc)
else:
raise RuntimeError("Expected unauthorized response, but dataset open operation did not raise!")
print("Unauthorized was raised as …
```
=> pavics_thredds.ipynb: update for new Jupyter env with xarray 0.20.1

docs/source/notebooks/climex.ipynb, docs/source/notebooks/subset-user-input.ipynb
`climex.ipynb` and `forecasts.ipynb` use the catalog that are not deployed on test servers.  We need to force the catalog from the production server for these notebooks to pass on test servers.
Finch 0.8.0 from PR https://github.com/bird-house/birdhouse-deploy/pull/231 seems to have changed the output url format, causing the following Jenkins error in `subset-user-input.ipynb`:
```
___ pavics-sdi-master/docs/source/notebooks/subset-user-input.ipynb::Cell 15 ___
Cell 15: Cell outputs differ
Input:
tasmin_subset = result_tasmin.get().output
tasmin_subset
Traceback:
mismatch 'text/plain'
"'https://WPS..._v2_sub.ncml'" == "'https://WPS...8fa_sub.ncml'"
Skipping 40 identical leading characters in diff, use -v to show …
```
=> Use catalog from prod and fix output url format change from Finch 0.8.0

docs/source/notebook-components/weaver_example.ipynb
Output Weaver's failing Job logs directly in the error message to help debugging the cause.
When running on Jenkins, collected artifacts actually contain the *expected* notebook outputs rather than *obtained* outputs... therefore it is impossible to debug the cause accordingly.
=> output job logs in assert message for test debuging

docs/source/notebooks/WFS_example.ipynb, docs/source/notebooks/regridding.ipynb
Switch from `boreas.ouranos.ca` to `pavics.ouranos.ca` will allow us to
conditionally regex replace `pavics.ouranos.ca` to the server under test
so we can actually test the Geoserver on that new server.
Everywhere under this pavics-sdi repo, we use `pavics.ouranos.ca`.  This
is the only locations that hardcode `boreas.ouranos.ca` because
geoserver data are not replicated to standard test servers so hardcoding
it this way will use the data from the production server.
This patch achieve the same "data from prod" but also allow override if
we need to actually test the future production server.
Related to https://github.com/Ouranosinc/pavics-sdi/issues/183 and https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/104.
Also fix old `nrcan_v2.ncml` path in `regridding.ipynb`.
=> notebooks: allow to test GeoServer on new production server and fix old .ncml path

docs/source/notebook-components/weaver_example.ipynb
Flagged during weaver test: http://daccs-jenkins.crim.ca/job/PAVICS-e2e-workflow-tests/job/master/763/console
Due to new `hourly_to_daily` in https://github.com/bird-house/finch/releases/tag/v0.8.0
```log
14:44:29  
14:44:29  Traceback:
14:44:29   mismatch 'stdout'
14:44:29  
14:44:29   assert reference_output == test_output failed:
14:44:29  
14:44:29    'Listing WPS ...zonal-stats\n' == 'Listing WPS ...zonal-stats\n'
14:44:29    Skipping 27555 identical leading characters in diff, use -v to show
14:44:29    + rocesses/growing_degree_days
14:44:29    - rocesses/geoseries_to_netcdf
14:44:29    -  - https://PAVICS_FQDN/weaver/providers/finch/processes/growing_degree_days
14:44:29       - https://PAVICS_FQDN/weaver/providers/finch/processes/growing_season_end
14:44:29       - …
```
=> add missing weaver-provider new finch 0.8.0 process

docs/source/notebook-components/weaver_example.ipynb
Another new process I missed in #255 
I ran the notebook against the current birdhouse-deploy master. 
Should be the last diff.
=> add missing `geoseries_to_netcdf` from `finch` provider in weaver notebook

docs/source/notebooks/climex.ipynb
Should have used the climex link on PAVICS prod server instead of the test server.
`TEST_USE_PROD_DATA` should be on the same line as "pavics.ouranos.ca" to avoid it being replaced by the test server during Jenkins run.
The precommit autoformatter should not break that line.
See previous fix that was lost, not sure why
https://github.com/Ouranosinc/pavics-sdi/commit/75652fbe9751bc1f2b85109daf44402533639e8b (PR https://github.com/Ouranosinc/pavics-sdi/pull/267)
Jenkins failure found in PR https://github.com/bird-house/birdhouse-deploy/pull/280#issuecomment-1404323983:
```
10:36:34  _________ pavics-sdi-master/docs/source/notebooks/climex.ipynb::Cell 0 _________
10:36:34  Notebook cell execution failed
10:36:34  Cell 0: Cell execution caused an exception
10:36:34  
10:36:34  Input:
10:36:34 …
```
=> climex.ipynb: fix Jenkins failure due to climex link on wrong server

environment.yml
=> Add pykdtree to environment to resolve cartopy bug arising from scipy 1.11

docs/source/notebook-components/weaver_example.ipynb
Ran the weaver notebook against an instance deployed with https://github.com/bird-house/birdhouse-deploy/pull/376 to obtain the response outputs without `flyingpigeon` processes, and replaced back the `PAVICS_FQDN` value by the original one in the notebook.
- relates to https://github.com/Ouranosinc/pavics-sdi/pull/303
- relates to https://github.com/bird-house/birdhouse-deploy/pull/376
=> fix weaver outputs with deprecated flyingpigeon removed

docs/source/notebook-components/weaver_example.ipynb
When running automated CI tests with E2E workflow, the JSON contents are not available directly. 
Add them to the assert error message to help debugging the cause.
=> output response body in assert message for debug during E2E tests

docs/source/notebooks/climex.ipynb
nbformat version 4.4 requires both `name` and `display_name` fields for the `kernelspec` key (https://github.com/jupyter/nbformat/blob/main/nbformat/v4/nbformat.v4.4.schema.json#L16).
This PR adds those to the climex.ipynb file where they appear to be missing so that tools, such as nbconvert, don't fail unexpectedly when trying to parse the metadata of this notebook.
=> fix kernelspec metadata for climex.ipynb

docs/source/notebooks/eccc-geoapi-xclim.ipynb
Fails Jenkins again, even after previous fix
https://github.com/Ouranosinc/pavics-sdi/pull/312 that was tested to work.
=> eccc-geoapi-xclim.ipynb: ignore output because it varies too much

docs/source/notebook-components/weaver_example.ipynb
Add the missing `/output` in the URL of the produced WPS output of Weaver.
=> update expected nested output id location for weaver wps outputs

docs/source/notebooks/subset-user-input.ipynb
Original commit was from Travis
https://github.com/Ouranosinc/pavics-sdi/pull/317/commits/0a76235d5bbef8e57ce061e50b47367d0a088f67
Replaces PR https://github.com/Ouranosinc/pavics-sdi/pull/317
To avoid this error when we will upgrade to Thredds v5, while being backward compatible with current Thredds v4:
```
15:47:13  ___ pavics-sdi-master/docs/source/notebooks/subset-user-input.ipynb::Cell 12 ___
15:47:13  Notebook cell execution failed
15:47:13  Cell 12: Cell outputs differ
15:47:13  
15:47:13  Input:
15:47:13  # gather data from the PAVICS data catalogue
15:47:13  catalog = "https://boreas.ouranos.ca/twitcher/ows/proxy/thredds/catalog/datasets/gridded_obs/catalog.xml"  # TEST_USE_PROD_DATA
15:47:13  
15:47:13  cat = TDSCatalog(catalog)
15:47:13  data = …
```
=> subset-user-input.ipynb: avoid dataset ordering change between Thredds v4 and v5

docs/source/notebooks/FAQ_dask_parallel.ipynb
We still want to "not ignore output" when displaying data to confirm correctness and detect unintentional data change on the server, ex cell 1.
@aslibese FYI pavics-sdi notebooks are being tested nightly by Jenkins (http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/) because they are automatically deployed to PAVICS as tutorial notebooks (https://pavics.ouranos.ca/jupyter/hub/user-redirect/lab/tree/tutorial-notebooks/FAQ_dask_parallel.ipynb) and we want to ensure our tutorial notebooks to always work for our end users.
Jenkins uses exactly the same Jupyter env deployed on PAVICS to run all the tutorial notebooks to ensure the runtime environment matches the notebooks.  It checks for no error and same output then the notebooks are run.  Therefore, for outputs that we don't …
=> FAQ nb: ignore output when not related to data display to avoid breaking Jenkins
